# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ee13020211d5b496fba816fae70907e4321c2b8647b6354c55ef7a1ff7f737b719caa3c1312f6ceb2626e4040f898950da62d46ce49b81f8565d4dbe3efd8b3

test:
  secret_key_base: 38a00bf85c2b83811c6b6b22329f3be1f00281438e49af4bfe999100b7a01eaff460b5a67bc013076a3a6c85c7e4796373481b52b48961e35630b68471cbb06b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
